clone of the intuit.com sign up form
mke2111/SignUpCR1230 pull request #1
Opened 2020-09-21 19:34 UTC by che30

We worked with the new feature branch "secondbranch" and designed the inuit.com sign up "look-alike" form using HTML and CSS

2020-09-21 20:50 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Good job on your project. I enjoyed reviewing it.**

**There are a few things that need to be done before it gets approved.**

# Mandatory

1). **Your clone doesn't have the intuit logo above the form.**

 clone |  original
------- | ---------
![intuit_clone](https://user-images.githubusercontent.com/38922385/93818946-b6f9af80-fc63-11ea-860d-bae84e806570.png) | ![intuit_original](https://user-images.githubusercontent.com/38922385/93819006-caa51600-fc63-11ea-8ce2-ace2fe4923e6.png)

2). **It doesn't display the mint logo, quickbooks logo and turbotax logo as shown above.**

3). **Add a Getting started section in your readme file and provide details on how one can set up your repo on their local computer, and the necessary tools required. Check the [readme template](https://github.com/microverseinc/readme-template) for more details on this.**

### Please check for more comments below.

## Good luck 😃.

### PS: Incase you want to reach out, please send me a message on slack (@Rose Wanjohi)

2020-09-21 20:50 UTC, blackpintz commented on index.html
> +                </form>
- The email should have an `<input>` of type `email`.

- The phone should have an `<input>` of type` tel`.

2020-09-21 20:50 UTC, blackpintz commented on style.css
> +    /* width: 100%; */
Remove comments in your css file.

2020-09-21 20:50 UTC, blackpintz commented on style.css
> +    /* background-color: ; */
Please remove these comments from your CSS file and any other comment that exists.

2020-09-21 20:50 UTC, blackpintz commented on index.html
> +        </footer>
The `<footer> `tag should not be inside the `<main>` tag.
```
<body>
    <header></header>
    <main></main>
    <footer></footer>
</body>
```

2020-09-21 22:14 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey team :+1: 

You did a great job here :100: 

The layout looks quite nice. However, it seems that you did not fixed what was previously requested in the last review. Check the inline comments below to see all the required changes with detail. Generally, you need to:

- [ ] remove all the comments

- [ ] Customize your readme

- [ ] Change your inputs

- [ ] Fix your HTML structure

Kindly check the inline comments for more details and changes to be made.

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-21 22:14 UTC, expjazz commented on style.css
> +    /* width: 100%; */
- [ ] You need to remove all the comments.

2020-09-21 22:14 UTC, expjazz commented on index.html
> +        <footer>
- [ ] You need to do what was asked by the previous TSE.

2020-09-21 22:14 UTC, expjazz commented on index.html
> +                        <input class="input-field" type="text" id="email"></div>
- [ ] You need to change this to email. Just like it was asked before

2020-09-21 22:14 UTC, expjazz commented on index.html
> +            <div class="logo"><img src="image/logo.png" alt="logo"></div>
- [ ] This should be divided by three, with each part with the respective logo and text. 

![image](https://user-images.githubusercontent.com/61479648/93826447-a1718f00-fc3d-11ea-86ab-61d6c766359c.png)

2020-09-21 22:14 UTC, expjazz commented on README.md
> +Contributions, issues, and feature requests are welcome!
- [ ] You still need to add the section that was previously asked.

2020-09-21 22:14 UTC, expjazz commented on README.md
> +
- [ ] You need to change this because it came from the template.

2020-09-22 00:04 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-22 00:10 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @happiguru AND @umairarshadbutt 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly implement the required changes as previous TSEs suggested.
- [ ] The phone should have an <input> of type tel.

- [ ] It shows the Mint logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)

- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)

- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-22 00:10 UTC, umairarshadbutt commented on index.html
> +                        <input class="input-field" type="number" id="phone">
The phone should have an <input> of type tel.

2020-09-22 00:10 UTC, umairarshadbutt commented on index.html
> +            <div class="logo"><img src="image/logo.png" alt="logo"></div>
- [ ] It shows the Mint logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)

- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)

- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) [link to page](https://accounts.intuit.com/signup.html)

2020-09-22 02:35 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of ---- 💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-09-22 02:49 UTC, merged